# deploy/ansible-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hobbyfarm-provisioner-ansible
  namespace: default
  labels:
    app: hobbyfarm-provisioner
data:
  base.yaml: |
    # Basic VM setup playbook content
    ---
    - name: Base VM Setup
      hosts: target
      become: yes
      tasks:
        - name: Update apt cache
          apt:
            update_cache: yes
            cache_valid_time: 3600
        
        - name: Install basic packages
          apt:
            name:
              - vim
              - curl
              - wget
              - git
              - htop
              - net-tools
              - python3
              - python3-pip
            state: present
  
  dynamic.yaml: |
    # Dynamic provisioning playbook content
    ---
    - name: Dynamic Session Provisioning
      hosts: target
      become: yes
      vars:
        session_user: "{{ session_name | default(ansible_hostname) }}"
        session_user_home: "/home/{{ session_user }}"
      tasks:
        - name: Create session-specific user
          user:
            name: "{{ session_user }}"
            home: "{{ session_user_home }}"
            shell: /bin/bash
            groups: sudo
            append: yes
            generate_ssh_key: yes
            state: present
