# deploy/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hobbyfarm-provisioner-ssh
  namespace: default
  labels:
    app: hobbyfarm-provisioner
type: Opaque
data:
  # Base64 encoded SSH private key for VM access
  # Replace with your actual SSH private key
  id_rsa: " " 
  id_rsa.pub: " " 
