# config/trainingvm-crd.yaml - FIXED VERSION with status subresource
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trainingvms.training.example.com
spec:
  group: training.example.com
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}  # Enable status subresource
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              user:
                type: string
              session:
                type: string
          status:
            type: object
            properties:
              vmIP:
                type: string
              state:
                type: string
              provisioned:
                type: boolean
              allocatedAt:
                type: string
              lastError:
                type: string
              retryCount:
                type: integer
  scope: Namespaced
  names:
    plural: trainingvms
    singular: trainingvm
    kind: TrainingVM

---
# TrainingVMRequest CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trainingvmrequests.training.example.com
spec:
  group: training.example.com
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}  # Enable status subresource
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              user:
                type: string
              session:
                type: string
          status:
            type: object
            properties:
              vmIP:
                type: string
              state:
                type: string
              instanceId:
                type: string
  scope: Namespaced
  names:
    plural: trainingvmrequests
    singular: trainingvmrequest
    kind: TrainingVMRequest
