# kratix/deployment/kratix-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hobbyfarm-provisioner-kratix-config
  namespace: default
  labels:
    app: hobbyfarm-provisioner
    component: kratix-integration
data:
  # Kratix-specific configuration
  kratix-config.yaml: |
    kratix:
      enabled: true
      integration_mode: "hybrid"
      hobbyfarm_direct_mode: false
      promise_name: "vm-provisioning"
      promise_namespace: "default"

    vm_provisioning:
      static_vm_pool:
        - "192.168.2.37"
        - "192.168.2.38"

      cloud_fallback:
        enabled: true
        providers:
          aws:
            region: "us-east-1"
            instance_type: "t3.micro"
            ami: "ami-0c02fb55956c7d316"
            key_name: "hobbyfarm-keypair"
            subnet_id: "subnet-09418e7f533840cde"
            security_group_ids: ["sg-0bfde988b4d5f8110"]
          azure:
            location: "eastus"
            vm_size: "Standard_B1s"
            image: "ubuntu-20.04"
          gcp:
            zone: "us-central1-a"
            machine_type: "e2-micro"
            image: "ubuntu-2004-lts"

    provisioning:
      ansible:
        timeout: "300s"
        retries: 5
        ssh_timeout: "120s"
        default_playbooks:
          - "base.yaml"
          - "dynamic.yaml"

      timeouts:
        allocation: "10m"
        provisioning: "15m"
        boot_wait_static: "30s"
        boot_wait_ec2: "2m"
        ssh_timeout_static: "2m"
        ssh_timeout_ec2: "5m"
